=== RavuAlHemio/bcusdk/xml/gui/configdesc.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- version 0.0.0 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.auto.tuwien.ac.at/~mkoegler/eib/xml/configdesc.xsd" targetNamespace="http://www.auto.tuwien.ac.at/~mkoegler/eib/xml/configdesc.xsd" elementFormDefault="qualified">
  <xs:simpleType name="Version">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+\.[0-9]+\.[0-9]+"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="PID">
    <xs:restriction base="xs:ID">
<!--*xs:string/xs:ID?-->
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="listelement">
    <xs:restriction base="xs:string">
<!--*-->
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="eibaddr">
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9]|1[0-5])\.([0-9]|1[0-5])\.([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="groupaddr">
    <xs:restriction base="xs:hexBinary">
      <xs:minLength value="1"/>
      <xs:maxLength value="4"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="pollingaddr">
    <xs:restriction base="xs:hexBinary">
      <xs:minLength value="1"/>
      <xs:maxLength value="4"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="pollingslot">
    <xs:restriction base="xs:nonNegativeInteger">
      <xs:maxInclusive value="15"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="pollingcount">
    <xs:restriction base="xs:nonNegativeInteger">
      <xs:maxInclusive value="15"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="keylevel">
    <xs:restriction base="xs:nonNegativeInteger">
      <xs:maxInclusive value="15"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="keytype">
    <xs:restriction base="xs:hexBinary">
      <xs:minLength value="1"/>
      <xs:maxLength value="8"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="priority">
    <xs:restriction base="xs:string">
      <xs:enumeration value="low"/>
      <xs:enumeration value="normal"/>
      <xs:enumeration value="urgent"/>
      <xs:enumeration value="system"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="DeviceConfig">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ProgramID" type="xs:string"/>
        <xs:element name="PhysicalAddress" type="eibaddr"/>
	<xs:element name="InstallKey" type="keytype"/>
        <xs:element name="Key" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="keytype">
                <xs:attribute name="id" type="keylevel"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element name="GroupObject">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Priority" type="priority" minOccurs="0"/>
                <xs:element name="SendAddress" type="groupaddr" minOccurs="0"/>
                <xs:element name="ReceiveAddress" minOccurs="0">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="GroupAddr" type="groupaddr" maxOccurs="unbounded"/>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
                <xs:element name="ReadAddress" minOccurs="0">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="GroupAddr" type="groupaddr" maxOccurs="unbounded"/>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
                <xs:element name="UpdateAddress" minOccurs="0">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="GroupAddr" type="groupaddr" maxOccurs="unbounded"/>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
              <xs:attribute name="id" type="PID"/>
            </xs:complexType>
          </xs:element>
          <xs:element name="Property">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Disable" type="xs:boolean" minOccurs="0"/>
                <xs:element name="ReadOnly" type="xs:boolean" minOccurs="0"/>
                <xs:element name="ReadAccess" type="keylevel" minOccurs="0"/>
                <xs:element name="WriteAccess" type="keylevel" minOccurs="0"/>
              </xs:sequence>
              <xs:attribute name="id" type="PID"/>
            </xs:complexType>
          </xs:element>
          <xs:element name="PollingMaster">
            <xs:complexType>
              <xs:sequence minOccurs="0">
                <xs:element name="PollingAddress" type="pollingaddr"/>
                <xs:element name="PollingCount" type="pollingcount"/>
              </xs:sequence>
              <xs:attribute name="id" type="PID"/>
            </xs:complexType>
          </xs:element>
          <xs:element name="PollingSlave">
            <xs:complexType>
              <xs:sequence minOccurs="0">
                <xs:element name="PollingAddress" type="pollingaddr"/>
                <xs:element name="PollingSlot" type="pollingslot"/>
              </xs:sequence>
              <xs:attribute name="id" type="PID"/>
            </xs:complexType>
          </xs:element>
        </xs:choice>
        <xs:element name="Parameter" minOccurs="0">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded">
              <xs:element name="ListParameter">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Value" type="listelement"/>
                  </xs:sequence>
                  <xs:attribute name="id" type="PID"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="IntParameter">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Value" type="xs:integer"/>
                  </xs:sequence>
                  <xs:attribute name="id" type="PID"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="FloatParameter">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Value" type="xs:decimal"/>
                  </xs:sequence>
                  <xs:attribute name="id" type="PID"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="StringParameter">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Value" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="id" type="PID"/>
                </xs:complexType>
              </xs:element>
            </xs:choice>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="version" type="Version"/>
    </xs:complexType>
    <xs:key name="uniqpar">
      <xs:selector xpath="Parameter/ListParameter|Parameter/IntParameter|Parameter/FloatParameter|Parameter/StringParameter|Property|GroupObject|PollingSlave|PollingMaster"/>
      <xs:field xpath="@id"/>
    </xs:key>
    <xs:key name="unikey">
      <xs:selector xpath="Key"/>
      <xs:field xpath="@id"/>
    </xs:key>
    <xs:keyref name="refkey" refer="unikey">
      <xs:selector xpath="Property/ReadAccess|Property/WriteAccess"/>
      <xs:field xpath="."/>
    </xs:keyref>
  </xs:element>
</xs:schema>

=== RavuAlHemio/bcusdk/xml/gui/examples/deviceconfig-1.xml
<?xml version="1.0"?>
<DeviceConfig xmlns:ns1="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.auto.tuwien.ac.at/~mkoegler/eib/xml/configdesc.xsd" version="0.0.0" ns1:schemaLocation="http://www.auto.tuwien.ac.at/~mkoegler/eib/xml/configdesc.xsd">
  <ProgramID>11234235r0fjdf9323</ProgramID>
  <PhysicalAddress>0.0.0</PhysicalAddress>
  <InstallKey>00000000</InstallKey>
  <Key id="1">00000000</Key>
  <GroupObject id="go1">
    <Priority>low</Priority>
    <SendAddress>0000</SendAddress>
    <ReceiveAddress>
      <GroupAddr>0000</GroupAddr>
    </ReceiveAddress>
    <ReadAddress>
      <GroupAddr>0000</GroupAddr>
    </ReadAddress>
    <UpdateAddress>
      <GroupAddr>0000</GroupAddr>
    </UpdateAddress>
  </GroupObject>
  <GroupObject id="go2">
    <Priority>low</Priority>
    <SendAddress>0000</SendAddress>
    <ReceiveAddress>
      <GroupAddr>0000</GroupAddr>
    </ReceiveAddress>
    <ReadAddress>
      <GroupAddr>0000</GroupAddr>
    </ReadAddress>
    <UpdateAddress>
      <GroupAddr>0000</GroupAddr>
    </UpdateAddress>
  </GroupObject>
  <Property id="p1">
    <Disable>false</Disable>
    <ReadOnly>false</ReadOnly>
    <ReadAccess>1</ReadAccess>
    <WriteAccess>1</WriteAccess>
  </Property>
  <Property id="p2">
    <Disable>false</Disable>
    <ReadOnly>false</ReadOnly>
    <ReadAccess>1</ReadAccess>
    <WriteAccess>1</WriteAccess>
  </Property>
  <PollingSlave id="ps1">
    <PollingAddress>0000</PollingAddress>
    <PollingSlot>0</PollingSlot>
  </PollingSlave>
  <PollingSlave id="ps2">
    <PollingAddress>0000</PollingAddress>
    <PollingSlot>0</PollingSlot>
  </PollingSlave>
  <PollingMaster id="pm1">
    <PollingAddress>0000</PollingAddress>
    <PollingCount>0</PollingCount>
  </PollingMaster>
  <PollingMaster id="pm2">
    <PollingAddress>0000</PollingAddress>
    <PollingCount>0</PollingCount>
  </PollingMaster>
  <Parameter>
    <ListParameter id="lp1">
      <Value>le1</Value>
    </ListParameter>
    <ListParameter id="lp2">
      <Value>le3</Value>
    </ListParameter>
    <IntParameter id="ip1">
      <Value>2</Value>
    </IntParameter>
    <IntParameter id="ip2">
      <Value>2222222</Value>
    </IntParameter>
    <FloatParameter id="fp1">
      <Value>2</Value>
    </FloatParameter>
    <FloatParameter id="fp2">
      <Value>1</Value>
    </FloatParameter>
    <StringParameter id="sp1">
      <Value>234</Value>
    </StringParameter>
    <StringParameter id="sp2">
      <Value>test</Value>
    </StringParameter>
  </Parameter>
</DeviceConfig>
